name: cinefouine
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0 
  auto_route: ^9.2.2
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  auto_route_generator: ^9.0.0
  flutter_svg: ^2.0.16
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.7.0
  meta: ^1.15.0
  shared_preferences: ^2.3.5
  intl: ^0.17.0
  signalr_netcore: ^1.4.0
  
dependency_overrides:
  web: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  json_serializable: ^6.9.0

flutter:
    uses-material-design: true
    assets:
    - assets/images/
    - assets/icons/